### ISSUE TITLE
'ENERGY' isn't a valid option for class 'FunctionalHomeType'

### ISSUE THREAD

**Issue by svensoltmann** [hahn-th/homematicip-rest-api#502]
Hello, I found in my Log-Files this Info:
---//---
Logger: homematicip.base.enums
Source: runner.py:186
First occurred: 08:14:32 (96 occurrences)
Last logged: 11:39:24

'ENERGY' isn't a valid option for class 'FunctionalHomeType'
---//---

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

thanks for your work,

Sven

**Comment by bapfnet** [comment]
Same here...
Maybe in junction with SSL: BAD_LENGTH ?

`WARNING:homematicip.base.enums:'ENERGY' isn't a valid option for class 'FunctionalHomeType'
ERROR:websocket:error from callback <bound method Home._ws_on_message of <homematicip.home.Home object at 0x7f287ed3a430>>: [SSL: BAD_LENGTH] bad length (_ssl.c:2485)
ERROR:homematicip.home:[SSL: BAD_LENGTH] bad length (_ssl.c:2485)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 553, in _callback
    callback(self, *args)
  File "/usr/local/lib/python3.8/site-packages/homematicip/home.py", line 864, in _ws_on_message
    self.onEvent.fire(eventList)
  File "/usr/local/lib/python3.8/site-packages/homematicip/EventHook.py", line 18, in fire
    handler(*args, **keywargs)
  File "/src/main.py", line 147, in onHomematicEvents
    updateHomematicObject(payload)
  File "/src/main.py", line 193, in updateHomematicObject
    client.publish(fullTopic, v, qos=0, retain=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.8/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2485)`

From python:3.8-alpine3.17

**Comment by hahn-th** [comment]
That should be fixed with Version 1.0.16. Which version do you use?
And please use python 3.9 - or better 3.11.

**Comment by bapfnet** [comment]
> That should be fixed with Version 1.0.16. Which version do you use? And please use python 3.9 - or better 3.11.

Thanks, I switched to python:3.11.6-alpine3.18 now.
Before I selected the very old Python version, there was an [ERROR: Could not build wheels for aiohttp...]

On my dockerfile:
RUN pip3 install --no-cache-dir python-dotenv paho-mqtt influxdb-client homematicip
RUN pip3 show homematicip
shows me Version: 1.0.16

**Comment by hahn-th** [comment]
Can you please upload your config dump?
